[package]
name = "common"
version = "0.0.1"
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
solana-program = "2.0.0"

[lints]
workspace = true
